services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=test.a@post.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - "./site/html:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"

      # Middleware redirection HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Router HTTP
      - "traefik.http.routers.frontend-http.rule=Host(`ducret.ovh`) || Host(`www.ducret.ovh`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"

      # Router HTTPS
      - "traefik.http.routers.frontend-https.rule=Host(`ducret.ovh`) || Host(`www.ducret.ovh`)"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls=true"
      - "traefik.http.routers.frontend-https.tls.certresolver=le"
    networks:
      - web
    restart: unless-stopped

networks:
  web: {}

volumes:
  letsencrypt: {}
